name: MineAnarquiaAntiIlegales
version: ${project.version}
main: com.danimania.mineanarquia.itemsilegales.Mineanarquia.ItemsIlegales
api-version: 1.16
authors: [danimania, gabboman, nekiak]
depend: [ProtocolLib]
commands:
  cama:
    description: Checkea tu punto de respawn.
  playtime:
    description: Checkea tu tiempo de juego.
