name: MineAnarquiaAntiIlegales
version: ${project.version}
main: com.danimania.mineanarquia.itemsilegales.Mineanarquia.ItemsIlegales
api-version: 1.16
authors: [danimania, gabboman, nekiak]
depend: [ProtocolLib]
commands: