name: MineAnarquiaAntiIlegales
version: ${project.version}
main: com.gabboman.mineanarquia.itemsilegales.Mineanarquia.ItemsIlegales
api-version: 1.17
authors: [gabboman, nekiak]
depend: [ProtocolLib]
commands:
  cama:
    description: Checkea tu punto de respawn.
  playtime:
    description: Checkea tu tiempo de juego.
  killstats:
    description: Checkea cuanta gente has matado.
